dist: trusty
language: cpp
env:
  global:
    secure: CYpfkGNx/dls+9YrO4IBc4QKX+8PF/+rQMWytj1EGuN9d3BqqC9uzTB7/oY8WOqwtI6tbxI4Nygv/IYw0h+hkOr1Sc3bSv+r0xZB3CNYbEZKrVOky5D/u+RGEyEMvNDfWDHP6a9A2VlzBn36W2gDYw9MQvtAu4KluxXGZxkv5tgFf57w+yZjq83ceQaNTyVSDOVy5rC3U+zc4X7tXrZOCT3vN/dKZPtsVjkHPbgy6zf89NE9h8RVBuGaIF+ML9RqzOCWyFrFcS5I60OMbq8wjbPUJ9P8rfUYEsEinP8jYYRxl3EYU6wHaQqRV68jX+zCIHS4aska13J0zzcAPuhVZLuaTx4XTOBCLOHR3XMIm2Kcx7UmU+yn+PSlbWohHzPf8nPBYQpWMK0cBEZQwRNZmHE2UEO3t9O6cNbiaPVu2nNjOW4XM0FS+a5Ky0uHZ7ViTSEBmwZwedI7gI5utWg1V/1nMFSpO5+sXn5I9FNsz4rlE2AUjMyxFTV7FYaZ8zVhZ6a1nCGMXshok/hByQPCao9/yBof+sCiqOM1xx0Z9Sotnp96/plOL4X2fYNQzPbkAIIJyKYmvAsY21aV8I8Y8gvbSO26Psv2Z6LxUdfYqCqD9apBJwpNVICu1ErUjn+gdX9n8vtnU4yJTjqMNFYgz9FWCHZ2iHCATbQCaBc+6O4=
python:
- '3.5'
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda config --add channels looooo
- conda config --add channels pybind
- conda config --add channels anaconda
- conda install --yes conda-build jinja2 anaconda-client anaconda-client
script:
- conda build ./packaging/conda
- conda install laplacekernels --use-local
after_success:
- anaconda -t $ANACONDA_TOKEN upload --user looooo /home/travis/miniconda/conda-bld/linux-64/laplacekernels-0.0.1-4.tar.bz2
