dist: trusty
language: cpp
compiler: g++

before_install:
  - hg clone https://bitbucket.org/eigen/eigen
  - sudo mkdir /usr/include/eigen3/
  - sudo cp eigen/Eigen/  /usr/include/eigen3/Eigen -r
  - sudo cp eigen/signature_of_eigen3_matrix_library /usr/include/eigen3/

install:
  - mkdir build
  - cd build
  - cmake .. -DMAKE_TEST=1
  - make

script:
  - build/src/test2D
  - build/src/test3D
