package:
  name: laplacekernels
  version: 0.0.1

build:
  number: 4

source:
  path: ../..

requirements:
  build:
    - python
    - pybind11
    - cmake
    - eigen           #   - https://conda.anaconda.org/rmg
    - vtk
  run:
    - python
    - vtk

about:
  summary: Some laplace kernels