package:
  name: laplacekernels
  version: 0.0.1

build:
  number: 2

source:
  path: ../..

requirements:
  build:
    - python
    - cmake
    - vtk

requirements:
  run:
    - python
    - vtk

about:
  summary: Some laplace kernels