package:
  name: laplacekernels
  version: 0.0.1

build:
  number: 3

source:
  path: ../

requirements:
  build:
    - python
    - cmake

requirements:
  run:
    - python

about:
  summary: Some laplace kernels